=== Andr3-2/pei/PaiNatal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Lista">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agendamento" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nr_elementos_familia" type="xs:string" />
                            <xs:element name="cidade" type="xs:string" />
                            <xs:element name="data">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string" />
                                        <xs:element name="mes" type="xs:string" />
                                        <xs:element name="ano" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="horas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hora" type="xs:string" />
                                        <xs:element name="minuto" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="membros">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="membro" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nome" type="xs:string" />
                                                    <xs:element name="nascimento">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="dia" type="xs:string" />
                                                                <xs:element name="mes" type="xs:string" />
                                                                <xs:element name="ano" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Andr3-2/pei/PaiNatal.xml
<?xml version="1.0" encoding="UTF-8"?>

<Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="PaiNatal.xsd">
    <agendamento>
        <nr_elementos_familia>3</nr_elementos_familia>
        <cidade>cidade</cidade>
        <data>
            <dia>12</dia>
            <mes>11</mes>
            <ano>2021</ano>
        </data>
        <horas>
            <hora>13</hora>
            <minuto>00</minuto>
        </horas>
        <membros>
            <membro>
                <nome>Pai</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>1</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
            <membro>
                <nome>Mae</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>2</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
            <membro>
                <nome>Filho</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>2</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
        </membros>
    </agendamento>

    <agendamento>
        <nr_elementos_familia>3</nr_elementos_familia>
        <cidade>cidade</cidade>
        <data>
            <dia>12</dia>
            <mes>11</mes>
            <ano>2021</ano>
        </data>
        <horas>
            <hora>13</hora>
            <minuto>00</minuto>
        </horas>
        <membros>
            <membro>
                <nome>Pai</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>1</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
            <membro>
                <nome>Mae</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>2</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
            <membro>
                <nome>Filho</nome>
                <nascimento>
                    <dia>1</dia>
                    <mes>2</mes>
                    <ano>1990</ano>
                </nascimento>
            </membro>
        </membros>
    </agendamento>

</Lista>
